### ISSUE TITLE
Documentation for AR0002 is confusing

### ISSUE THREAD

**Issue by j2jensen** [BrunoJuchli/StyleCop.CSharp.Async.Rules#5]
AR0002 is called "MethodEndingWithAsyncMustHaveAsyncModifierOrReturnTask", and it's [documented](https://github.com/BrunoJuchli/StyleCop.CSharp.Async.Rules/#methods-ending-with-async-must-have-async-modifier-or-return-a-task) thus:

> Violated when a method named `FooAsync` does not have the `async` modifier and does not return a `Task` / `Task<T>`.

I also note there's a bit about it recently getting adapted and renamed. 

This all would make me think that this rule should ignore methods returning a `Task` even if they have no `async` modifier. But there are other parts of the Readme that lead one to think it'll produce an error for those methods. For example, the [suppress warning in code](https://github.com/BrunoJuchli/StyleCop.CSharp.Async.Rules#suppress-specific-warning--occurrence-in-code-1) snippet uses a method returning a `Task` as an example of one requiring this method to be suppressed. And the summary bullet points at the top include:

- **`Task DoSomethingAsync()` --> method should have `async` modifier**

So what is the actual behavior of this rule?

**Comment by BrunoJuchli** [comment]
It took me a while but I've now fixed the documentation.
The rule is fulfilled when there's a `async` modifier *or* the method returns a `Task` or `Task<T>`.
