### ISSUE TITLE
nuget install failed.

### ISSUE THREAD

**Issue by lonelam** [BrunoJuchli/StyleCop.CSharp.Async.Rules#6]
hi, I can't install the package by visual studio 2017.

It seems the package is not available.

```
Each package is licensed to you by its owner. NuGet is not responsible for, nor does it grant any licenses to, third-party packages. Some packages may include dependencies which are governed by additional licenses. Follow the package source (feed) URL to determine any dependencies.

Package Manager Console Host Version 4.9.2.5706

Type 'get-help NuGet' to see all available NuGet commands.

PM> Install-Package StyleCop.CSharp.Async.Rules -Version 1.0.32


Attempting to gather dependency information for package 'StyleCop.CSharp.Async.Rules.1.0.32' with respect to project 'ObserveFoobar', targeting '.NETFramework,Version=v4.5.1'
Install-Package : Package 'StyleCop.CSharp.Async.Rules 1.0.32' is not found in the following primary source(s): 'https://api.nuget.org/v3/index.json,C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'. Please v
erify all your online package sources are available (OR) package id, version are specified correctly.
At line:1 char:1
+ Install-Package StyleCop.CSharp.Async.Rules -Version 1.0.32
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:01.1181875
PM> 
```

**Comment by BrunoJuchli** [comment]
Installing by VS2017 in a newly created .Net Framework library project works for me:
By Nuget Package Manager GUI:

> Attempting to gather dependency information for package 'StyleCop.CSharp.Async.Rules.1.0.32' with respect to project 'StyleCopAyncPackageTest', targeting '.NETFramework,Version=v4.7.2'
> Gathering dependency information took 88.03 ms
> Attempting to resolve dependencies for package 'StyleCop.CSharp.Async.Rules.1.0.32' with DependencyBehavior 'Lowest'
> Resolving dependency information took 0 ms
> Resolving actions to install package 'StyleCop.CSharp.Async.Rules.1.0.32'
> Resolved actions to install package 'StyleCop.CSharp.Async.Rules.1.0.32'
> Retrieving package 'StyleCop.CSharp.Async.Rules 1.0.32' from 'nuget.org'.
>   GET https://api.nuget.org/v3-flatcontainer/stylecop.csharp.async.rules/1.0.32/stylecop.csharp.async.rules.1.0.32.nupkg
>   OK https://api.nuget.org/v3-flatcontainer/stylecop.csharp.async.rules/1.0.32/stylecop.csharp.async.rules.1.0.32.nupkg 572ms
> Installing StyleCop.CSharp.Async.Rules 1.0.32.
> Adding package 'StyleCop.CSharp.Async.Rules.1.0.32' to folder 'C:\Users\BrunoJuchli\source\repos\StyleCopAyncPackageTest\packages'
> Added package 'StyleCop.CSharp.Async.Rules.1.0.32' to folder 'C:\Users\BrunoJuchli\source\repos\StyleCopAyncPackageTest\packages'
> Added package 'StyleCop.CSharp.Async.Rules.1.0.32' to 'packages.config'
> Successfully installed 'StyleCop.CSharp.Async.Rules 1.0.32' to StyleCopAyncPackageTest
> Executing nuget actions took 1.81 sec
> Time Elapsed: 00:00:02.1093615
> ========== Finished ==========

By console:

> Package Manager Console Host Version 4.9.2.5706
> 
> Type 'get-help NuGet' to see all available NuGet commands.
> 
> PM> Install-Package StyleCop.CSharp.Async.Rules -Version 1.0.32
> 
> 
> Attempting to gather dependency information for package 'StyleCop.CSharp.Async.Rules.1.0.32' with respect to project 'StyleCopAyncPackageTest', targeting '.NETFramework,Version=v4.7.2'
> Gathering dependency information took 2.31 ms
> Attempting to resolve dependencies for package 'StyleCop.CSharp.Async.Rules.1.0.32' with DependencyBehavior 'Lowest'
> Resolving dependency information took 0 ms
> Resolving actions to install package 'StyleCop.CSharp.Async.Rules.1.0.32'
> Resolved actions to install package 'StyleCop.CSharp.Async.Rules.1.0.32'
> Retrieving package 'StyleCop.CSharp.Async.Rules 1.0.32' from 'nuget.org'.
> Adding package 'StyleCop.CSharp.Async.Rules.1.0.32' to folder 'C:\Users\BrunoJuchli\source\repos\StyleCopAyncPackageTest\packages'
> Added package 'StyleCop.CSharp.Async.Rules.1.0.32' to folder 'C:\Users\BrunoJuchli\source\repos\StyleCopAyncPackageTest\packages'
> Added package 'StyleCop.CSharp.Async.Rules.1.0.32' to 'packages.config'
> Successfully installed 'StyleCop.CSharp.Async.Rules 1.0.32' to StyleCopAyncPackageTest
> Executing nuget actions took 981.83 ms
> Time Elapsed: 00:00:01.1199507

Trying to install an *inexisting* package yields the following on my setup:

> PM> Install-Package THISDOESNOTEXIST -Version 1.0.32
> 
> Attempting to gather dependency information for package 'THISDOESNOTEXIST.1.0.32' with respect to project 'StyleCopAyncPackageTest', targeting '.NETFramework,Version=v4.7.2'
> Install-Package : Package 'THISDOESNOTEXIST 1.0.32' is not found in the following primary source(s): 'https://api.nuget.org/v3/index.json,C:\Users\BrunoJuchli\.dotnet\NuGetFallbackFolder,C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'. Please verify all your online 
> package sources are available (OR) package id, version are specified correctly.
> At line:1 char:1
> + Install-Package THISDOESNOTEXIST -Version 1.0.32
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Time Elapsed: 00:00:00.7842478

--------

Looks like there was a temporary issue with the nuget feed or with your network connection.
Therefore I'll close this. Please provide feedback if I'm wrong.
