### ISSUE TITLE
Support for StyleCop.Analyzers

### ISSUE THREAD

**Issue by d-strickland** [BrunoJuchli/StyleCop.CSharp.Async.Rules#7]
Hi, the README recommends using `StyleCop.MSBuild`. Do these analyzers also work with `StyleCop.Analyzers`? I tried adding `StyleCop.Analyzers` and `StyleCop.CSharp.Async.Rules` to my project. They both installed OK, but the async analyzers weren't applied to my code.

I'm on macOS, and I tested both in JetBrains Rider and Visual Studio for Mac.

**Comment by BrunoJuchli** [comment]
Hi
StyleCop.CSharp.Async.Rules is for classic StyleCop and does not work with StyleCop.Analyzers.
StyleCop.Analyzers are Roslyn based Analyzers, while classic StyleCop did code introspection with it's own engine. StyleCop.CSharp.Async.Rules acts like a plugin to classic StyleCop.

For new projects, I recommend using [AsyncUsageAnalyzers](https://www.nuget.org/packages/AsyncUsageAnalyzers/1.0.0-alpha003). Don't mind it's an alpha version. We've been using it for several years and it works fine.
