### ISSUE TITLE
Not working with asp net core 3.1 and Visual 2019

### ISSUE THREAD

**Issue by smariano88** [BrunoJuchli/StyleCop.CSharp.Async.Rules#9]
Is it still compatible? Last update was a long time ago

**Comment by BrunoJuchli** [comment]
This is a ruleset for use with the original [stylecop](https://github.com/StyleCop/StyleCop).

For .net core you should go with [StyleCop.Analyzers](https://github.com/DotNetAnalyzers/StyleCopAnalyzers).

This project/package is not compatible with StyleCop.Analyzers and I have no plans to make it compatible.
Probably there's roslyn based rules for async, have a look at https://github.com/DotNetAnalyzers
